# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main-layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 460)
        self.MainBackground = QtWidgets.QFrame(MainWindow)
        self.MainBackground.setEnabled(True)
        self.MainBackground.setGeometry(QtCore.QRect(20, 10, 571, 441))
        self.MainBackground.setStyleSheet("QFrame {\n"
"    height:100%; margin:0;\n"
"    background-color: #ca3767;\n"
"    border-radius: 30px;\n"
"}")
        self.MainBackground.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBackground.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBackground.setObjectName("MainBackground")
        self.MainFrame_2 = QtWidgets.QFrame(self.MainBackground)
        self.MainFrame_2.setEnabled(True)
        self.MainFrame_2.setGeometry(QtCore.QRect(510, 0, 61, 441))
        self.MainFrame_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.MainFrame_2.setMouseTracking(False)
        self.MainFrame_2.setTabletTracking(False)
        self.MainFrame_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.MainFrame_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.MainFrame_2.setAcceptDrops(False)
        self.MainFrame_2.setStyleSheet("QFrame {\n"
"    border: 0;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 30px; \n"
"}")
        self.MainFrame_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.MainFrame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MainFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame_2.setObjectName("MainFrame_2")
        self.LogoType = QtWidgets.QFrame(self.MainBackground)
        self.LogoType.setGeometry(QtCore.QRect(10, 390, 31, 31))
        self.LogoType.setStyleSheet("QFrame {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    image: url(:/appIcon.png);\n"
"}")
        self.LogoType.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LogoType.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LogoType.setObjectName("LogoType")
        self.TextLogoType = QtWidgets.QLabel(self.MainBackground)
        self.TextLogoType.setGeometry(QtCore.QRect(47, 395, 101, 21))
        self.TextLogoType.setStyleSheet("QFrame {\n"
"    background-color: 0;\n"
"    color: white;\n"
"    font: 500 12pt \"Montserrat Medium\";    \n"
"}\n"
"")
        self.TextLogoType.setObjectName("TextLogoType")
        self.MainFrame = QtWidgets.QFrame(self.MainBackground)
        self.MainFrame.setEnabled(True)
        self.MainFrame.setGeometry(QtCore.QRect(150, 0, 391, 481))
        self.MainFrame.setAutoFillBackground(False)
        self.MainFrame.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border: 0;\n"
"    border-radius: 0;\n"
"}")
        self.MainFrame.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.MainFrame.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.line = QtWidgets.QFrame(self.MainFrame)
        self.line.setGeometry(QtCore.QRect(20, 110, 300, 3))
        self.line.setAutoFillBackground(False)
        self.line.setStyleSheet("QFrame {\n"
"    background-color: #ca3767;\n"
"}\n"
"")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.UserFullName = QtWidgets.QLabel(self.MainFrame)
        self.UserFullName.setGeometry(QtCore.QRect(24, 67, 291, 21))
        self.UserFullName.setStyleSheet("QFrame {\n"
"    background-color: 0;\n"
"    color: #ca3767;\n"
"    font: 500 9pt \"Montserrat Medium\";    \n"
"}\n"
"")
        self.UserFullName.setObjectName("UserFullName")
        self.GetUserFullName = QtWidgets.QLineEdit(self.MainFrame)
        self.GetUserFullName.setGeometry(QtCore.QRect(25, 87, 291, 22))
        self.GetUserFullName.setTabletTracking(False)
        self.GetUserFullName.setAutoFillBackground(False)
        self.GetUserFullName.setStyleSheet("QLineEdit {\n"
"    background-color: 0;\n"
"    color: #ca3767;\n"
"    border: 0;\n"
"    font: 500 9pt \"Montserrat Medium\";    \n"
"}\n"
"")
        self.GetUserFullName.setInputMask("")
        self.GetUserFullName.setText("")
        self.GetUserFullName.setMaxLength(60)
        self.GetUserFullName.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.GetUserFullName.setCursorPosition(0)
        self.GetUserFullName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.GetUserFullName.setDragEnabled(False)
        self.GetUserFullName.setReadOnly(False)
        self.GetUserFullName.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.GetUserFullName.setClearButtonEnabled(False)
        self.GetUserFullName.setObjectName("GetUserFullName")
        self.SIGNUP = QtWidgets.QLabel(self.MainFrame)
        self.SIGNUP.setGeometry(QtCore.QRect(23, 17, 301, 31))
        self.SIGNUP.setStyleSheet("QFrame {\n"
"    background-color: 0;\n"
"    color: #ca3767;\n"
"    font: 500 16pt \"Montserrat Medium\";    \n"
"}\n"
"")
        self.SIGNUP.setObjectName("SIGNUP")
        self.DateUser = QtWidgets.QLabel(self.MainFrame)
        self.DateUser.setGeometry(QtCore.QRect(24, 137, 171, 21))
        self.DateUser.setStyleSheet("QFrame {\n"
"    background-color: 0;\n"
"    color: #ca3767;\n"
"    font: 500 9pt \"Montserrat Medium\";    \n"
"}\n"
"")
        self.DateUser.setObjectName("DateUser")
        self.line_2 = QtWidgets.QFrame(self.MainFrame)
        self.line_2.setGeometry(QtCore.QRect(20, 180, 300, 3))
        self.line_2.setAutoFillBackground(False)
        self.line_2.setStyleSheet("QFrame {\n"
"    background-color: #ca3767;\n"
"}\n"
"")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.DateEditUser = QtWidgets.QDateEdit(self.MainFrame)
        self.DateEditUser.setGeometry(QtCore.QRect(28, 160, 71, 20))
        self.DateEditUser.setStyleSheet("QDateEdit {\n"
"    background-color: 0;\n"
"    color: #ca3767;\n"
"    border: 0;\n"
"    font: 500 9pt \"Montserrat Medium\";    \n"
"}\n"
"")
        self.DateEditUser.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.DateEditUser.setWrapping(False)
        self.DateEditUser.setFrame(True)
        self.DateEditUser.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.DateEditUser.setReadOnly(False)
        self.DateEditUser.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.DateEditUser.setMaximumDate(QtCore.QDate(3000, 12, 31))
        self.DateEditUser.setMinimumDate(QtCore.QDate(1799, 9, 14))
        self.DateEditUser.setObjectName("DateEditUser")
        self.SignUpClinicButton = QtWidgets.QPushButton(self.MainFrame)
        self.SignUpClinicButton.setEnabled(False)
        self.SignUpClinicButton.setGeometry(QtCore.QRect(20, 280, 300, 24))
        self.SignUpClinicButton.setStyleSheet("QPushButton {\n"
"    background-color: #ca3767;\n"
"    color: white;\n"
"    border: 0;\n"
"    font: 500 10pt \"Montserrat Medium\";    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #CA378A;\n"
"}\n"
"\n"
"QPushButton:disabled,\n"
"QPushButton[disabled]{\n"
"  background-color: #c298a6;\n"
"  color: white;\n"
"}")
        self.SignUpClinicButton.setObjectName("SignUpClinicButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.MainFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(340, 0, 51, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rubutton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.rubutton_2.setStyleSheet("QPushButton {\n"
"    border: 0;\n"
"    color: #ca3767;\n"
"    font: 9pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #CA378A;\n"
"    border-radius: 2px;\n"
"    color: white;\n"
"}")
        self.rubutton_2.setObjectName("rubutton_2")
        self.horizontalLayout.addWidget(self.rubutton_2)
        self.rubutton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.rubutton.setStyleSheet("QPushButton {\n"
"    border: 0;\n"
"    color: #ca3767;\n"
"    font: 9pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #CA378A;\n"
"    border-radius: 2px;\n"
"    color: white;\n"
"}")
        self.rubutton.setObjectName("rubutton")
        self.horizontalLayout.addWidget(self.rubutton)
        self.DateUser_2 = QtWidgets.QLabel(self.MainFrame)
        self.DateUser_2.setGeometry(QtCore.QRect(24, 196, 171, 21))
        self.DateUser_2.setStyleSheet("QFrame {\n"
"    background-color: 0;\n"
"    color: #ca3767;\n"
"    font: 500 9pt \"Montserrat Medium\";    \n"
"}\n"
"")
        self.DateUser_2.setObjectName("DateUser_2")
        self.line_3 = QtWidgets.QFrame(self.MainFrame)
        self.line_3.setGeometry(QtCore.QRect(20, 239, 300, 3))
        self.line_3.setAutoFillBackground(False)
        self.line_3.setStyleSheet("QFrame {\n"
"    background-color: #ca3767;\n"
"}\n"
"")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.DateEditUser_2 = QtWidgets.QDateEdit(self.MainFrame)
        self.DateEditUser_2.setGeometry(QtCore.QRect(80, 219, 71, 20))
        self.DateEditUser_2.setStyleSheet("QDateEdit {\n"
"    background-color: 0;\n"
"    color: #ca3767;\n"
"    border: 0;\n"
"    font: 500 9pt \"Montserrat Medium\";    \n"
"}\n"
"")
        self.DateEditUser_2.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.DateEditUser_2.setWrapping(False)
        self.DateEditUser_2.setFrame(True)
        self.DateEditUser_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.DateEditUser_2.setReadOnly(False)
        self.DateEditUser_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.DateEditUser_2.setMaximumDate(QtCore.QDate(3000, 12, 31))
        self.DateEditUser_2.setMinimumDate(QtCore.QDate(1799, 9, 14))
        self.DateEditUser_2.setObjectName("DateEditUser_2")
        self.timeEdit = QtWidgets.QTimeEdit(self.MainFrame)
        self.timeEdit.setGeometry(QtCore.QRect(30, 217, 41, 22))
        self.timeEdit.setStyleSheet("QTimeEdit {\n"
"    background-color: 0;\n"
"    color: #ca3767;\n"
"    border: 0;\n"
"    font: 500 9pt \"Montserrat Medium\";    \n"
"}\n"
"")
        self.timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit.setObjectName("timeEdit")
        self.DateUser_3 = QtWidgets.QLabel(self.MainFrame)
        self.DateUser_3.setGeometry(QtCore.QRect(67, 216, 16, 21))
        self.DateUser_3.setStyleSheet("QFrame {\n"
"    background-color: 0;\n"
"    color: #ca3767;\n"
"    font: 500 9pt \"Montserrat Medium\";    \n"
"}\n"
"")
        self.DateUser_3.setObjectName("DateUser_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.MainBackground)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 151, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.HomeButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.HomeButton.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: white;\n"
"    height: 40;\n"
"    border: 0;\n"
"}\n"
"")
        self.HomeButton.setObjectName("HomeButton")
        self.verticalLayout.addWidget(self.HomeButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.MySend = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.MySend.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: 0;\n"
"    height: 40;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: black;\n"
"    background-color: white;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"")
        self.MySend.setObjectName("MySend")
        self.verticalLayout.addWidget(self.MySend)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.SettingButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SettingButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: 0;\n"
"    height: 40;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: black;\n"
"    background-color: white;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"")
        self.SettingButton.setObjectName("SettingButton")
        self.verticalLayout.addWidget(self.SettingButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.HideProgram = QtWidgets.QPushButton(self.MainBackground)
        self.HideProgram.setGeometry(QtCore.QRect(60, 1, 31, 31))
        self.HideProgram.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.HideProgram.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.HideProgram.setStyleSheet("QPushButton {\n"
"    border: 0;\n"
"    color: white;\n"
"    font: 900 15pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-radius: 7px;\n"
"    background-color: #a85973;\n"
"}")
        self.HideProgram.setCheckable(False)
        self.HideProgram.setChecked(False)
        self.HideProgram.setAutoRepeat(False)
        self.HideProgram.setAutoExclusive(False)
        self.HideProgram.setAutoDefault(False)
        self.HideProgram.setObjectName("HideProgram")
        self.CloseProgram = QtWidgets.QPushButton(self.MainBackground)
        self.CloseProgram.setGeometry(QtCore.QRect(25, 1, 31, 31))
        self.CloseProgram.setStyleSheet("QPushButton {\n"
"    border: 0;\n"
"    color: white;\n"
"    font: 15pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-radius: 7px;\n"
"    background-color: #a85973;\n"
"}\n"
"")
        self.CloseProgram.setObjectName("CloseProgram")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.TextLogoType.setText(_translate("MainWindow", "КлиникБук"))
        self.UserFullName.setText(_translate("MainWindow", "Фамилия, Имя, Отчество:"))
        self.GetUserFullName.setPlaceholderText(_translate("MainWindow", "ФИО"))
        self.SIGNUP.setText(_translate("MainWindow", "Запись на приём"))
        self.DateUser.setText(_translate("MainWindow", "Дата рождения:"))
        self.SignUpClinicButton.setText(_translate("MainWindow", "Записаться"))
        self.rubutton_2.setText(_translate("MainWindow", "EN"))
        self.rubutton.setText(_translate("MainWindow", "RU"))
        self.DateUser_2.setText(_translate("MainWindow", "Время записи"))
        self.DateUser_3.setText(_translate("MainWindow", "::"))
        self.HomeButton.setText(_translate("MainWindow", "Главная"))
        self.MySend.setText(_translate("MainWindow", "Мои записи"))
        self.SettingButton.setText(_translate("MainWindow", "Настройки"))
        self.HideProgram.setText(_translate("MainWindow", "–"))
        self.CloseProgram.setText(_translate("MainWindow", "🞬"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
