# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\not_connected.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(567, 469)
        self.MainBackground = QtWidgets.QFrame(MainWindow)
        self.MainBackground.setEnabled(True)
        self.MainBackground.setGeometry(QtCore.QRect(20, 10, 571, 441))
        self.MainBackground.setStyleSheet("QFrame {\n"
"    height:100%; margin:0;\n"
"    background-color: #ca3767;\n"
"    border-radius: 30px;\n"
"}")
        self.MainBackground.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBackground.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBackground.setObjectName("MainBackground")
        self.WhiteColor = QtWidgets.QFrame(self.MainBackground)
        self.WhiteColor.setEnabled(True)
        self.WhiteColor.setGeometry(QtCore.QRect(260, 0, 311, 441))
        self.WhiteColor.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.WhiteColor.setMouseTracking(False)
        self.WhiteColor.setTabletTracking(False)
        self.WhiteColor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.WhiteColor.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.WhiteColor.setAcceptDrops(False)
        self.WhiteColor.setStyleSheet("QFrame {\n"
"    border: 0;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 30px; \n"
"}")
        self.WhiteColor.setInputMethodHints(QtCore.Qt.ImhNone)
        self.WhiteColor.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.WhiteColor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WhiteColor.setObjectName("WhiteColor")
        self.frame = QtWidgets.QFrame(self.WhiteColor)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, -10, 281, 481))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border: 0;\n"
"    border-radius: 0;\n"
"}")
        self.frame.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.frame.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(5)
        self.frame.setObjectName("frame")
        self.MainText = QtWidgets.QLabel(self.frame)
        self.MainText.setGeometry(QtCore.QRect(18, 30, 251, 31))
        self.MainText.setStyleSheet("QFrame {\n"
"    background-color: 0;\n"
"    color: #ca3767;\n"
"    font: 500 11pt \"Montserrat Medium\";    \n"
"}\n"
"")
        self.MainText.setObjectName("MainText")
        self.ReloadButton = QtWidgets.QPushButton(self.frame)
        self.ReloadButton.setGeometry(QtCore.QRect(20, 200, 241, 24))
        self.ReloadButton.setStyleSheet("QPushButton {\n"
"    background-color: #ca3767;\n"
"    color: white;\n"
"    border: 0;\n"
"    font: 500 10pt \"Montserrat Medium\";    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #CA378A;\n"
"}\n"
"")
        self.ReloadButton.setObjectName("ReloadButton")
        self.Texts = QtWidgets.QLabel(self.frame)
        self.Texts.setGeometry(QtCore.QRect(20, 70, 241, 111))
        self.Texts.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Texts.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Texts.setAcceptDrops(False)
        self.Texts.setStyleSheet("QFrame {\n"
"    background-color: 0;\n"
"    color: #ca3767;\n"
"    font: 500 9pt \"Montserrat Medium\";    \n"
"}\n"
"")
        self.Texts.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Texts.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Texts.setTextFormat(QtCore.Qt.AutoText)
        self.Texts.setScaledContents(False)
        self.Texts.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Texts.setWordWrap(True)
        self.Texts.setOpenExternalLinks(False)
        self.Texts.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.Texts.setObjectName("Texts")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setWindowModality(QtCore.Qt.NonModal)
        self.line.setGeometry(QtCore.QRect(19, 180, 241, 2))
        self.line.setStyleSheet("QFrame {\n"
"    background-color: #ca3767;\n"
"}\n"
"")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame_2 = QtWidgets.QFrame(self.MainBackground)
        self.frame_2.setGeometry(QtCore.QRect(55, 96, 151, 171))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    image: url(:/appIcon.png);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.ClinicBook = QtWidgets.QLabel(self.MainBackground)
        self.ClinicBook.setGeometry(QtCore.QRect(23, 246, 220, 81))
        self.ClinicBook.setStyleSheet("QFrame {\n"
"    background-color: 0;\n"
"    color: white;\n"
"    font: 500 28pt \"Montserrat Medium\";    \n"
"}\n"
"")
        self.ClinicBook.setObjectName("ClinicBook")
        self.CloseProgram = QtWidgets.QPushButton(self.MainBackground)
        self.CloseProgram.setGeometry(QtCore.QRect(25, 1, 31, 31))
        self.CloseProgram.setStyleSheet("QPushButton {\n"
"    border: 0;\n"
"    color: white;\n"
"    font: 15pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-radius: 7px;\n"
"    background-color: #a85973;\n"
"}\n"
"")
        self.CloseProgram.setObjectName("CloseProgram")
        self.HideProgram = QtWidgets.QPushButton(self.MainBackground)
        self.HideProgram.setGeometry(QtCore.QRect(59, 1, 31, 31))
        self.HideProgram.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.HideProgram.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.HideProgram.setStyleSheet("QPushButton {\n"
"    border: 0;\n"
"    color: white;\n"
"    font: 900 15pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-radius: 7px;\n"
"    background-color: #a85973;\n"
"}")
        self.HideProgram.setCheckable(False)
        self.HideProgram.setChecked(False)
        self.HideProgram.setAutoRepeat(False)
        self.HideProgram.setAutoExclusive(False)
        self.HideProgram.setAutoDefault(False)
        self.HideProgram.setObjectName("HideProgram")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.MainText.setText(_translate("MainWindow", "Нет подключения к интернету"))
        self.ReloadButton.setText(_translate("MainWindow", "reload"))
        self.Texts.setText(_translate("MainWindow", "К сожалению, в данный момент отсутствует подключение к интернету. Для работы этой программы требуется активное интернет-соединение. Пожалуйста, проверьте свое подключение и повторите попытку позже."))
        self.ClinicBook.setText(_translate("MainWindow", "КлиникБук"))
        self.CloseProgram.setText(_translate("MainWindow", "🞬"))
        self.HideProgram.setText(_translate("MainWindow", "–"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
